// 生成版本信息到 shared/version.generated.ts
// 供主进程日志和渲染进程 UI 共用，build/dist 前自动执行
const { execSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

const APP_VERSION = '0.1.9';
const APP_RELEASE_DIR = 'release-v019';

let commit = 'unknown';
try {
  commit = execSync('git rev-parse --short HEAD').toString().trim();
} catch {
  commit = 'dev-' + Date.now().toString(36);
}

const buildTime = new Date().toISOString().replace('T', ' ').slice(0, 16);

const content = `// AUTO-GENERATED by scripts/gen-version.js — 请勿手动编辑
export const APP_COMMIT = ${JSON.stringify(commit)};
export const APP_BUILD_TIME = ${JSON.stringify(buildTime)};
`;

const outPath = path.resolve(__dirname, '..', 'shared', 'version.generated.ts');
fs.writeFileSync(outPath, content, 'utf8');
console.log(`[gen-version] version=${APP_VERSION} commit=${commit} buildTime=${buildTime} -> ${outPath}`);
