// 生成版本信息到 shared/version.generated.ts
// 供主进程日志和渲染进程 UI 共用，build/dist 前自动执行
const { execSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

// 从 package.json 读取版本，避免多处硬编码不同步
const pkg = JSON.parse(
  fs.readFileSync(path.resolve(__dirname, '..', 'package.json'), 'utf8'),
);
const APP_VERSION = pkg.version;
const APP_RELEASE_DIR = `release-v${APP_VERSION.replace(/\./g, '')}`;

let commit = 'unknown';
try {
  commit = execSync('git rev-parse --short HEAD').toString().trim();
} catch {
  commit = 'dev-' + Date.now().toString(36);
}

const buildTime = new Date().toISOString().replace('T', ' ').slice(0, 16);

const content = `// AUTO-GENERATED by scripts/gen-version.js — 请勿手动编辑
export const APP_COMMIT = ${JSON.stringify(commit)};
export const APP_BUILD_TIME = ${JSON.stringify(buildTime)};
`;

const outPath = path.resolve(__dirname, '..', 'shared', 'version.generated.ts');
fs.writeFileSync(outPath, content, 'utf8');
console.log(`[gen-version] version=${APP_VERSION} commit=${commit} buildTime=${buildTime} -> ${outPath}`);
